### ISSUE TITLE
gem `thor` version conflicts with `license_finder` version of `thor`

### ISSUE THREAD

**Issue by hwo411** [emsk/bundle_outdated_formatter#5]
Bundler could not find compatible versions for gem "thor":
In snapshot (Gemfile.lock):
thor (= 0.20.3)

In Gemfile:
bundle_outdated_formatter (>= 0.5.1) was resolved to 0.6.0, which depends on
thor (~> 0.20)

license_finder (= 6.1.2) was resolved to 6.1.2, which depends on
  thor (~> 1.0.1)

Could you update it please?

**Comment by emsk** [comment]
@hwo411 Thank you for the suggestion.
Also, I'm sorry for my late reply 🙇 
I'm going to release a new version of this gem in a few days.

**Comment by emsk** [comment]
@hwo411 I just released v0.7.0 💎
Please try it 😄

**Comment by hwo411** [comment]
@emsk thanks! I'll try it next week.
